/**
 * seedData.js — Realistic prototype dataset for Legal Metrology (e-माप)
 * Derived from seed (1).js
 */

export const INITIAL_USERS = [
  {
    id: "usr-admin-1",
    email: "admin@legalmetrology.gov.in",
    role: "admin",
    name: "Anjali Desai",
    designation: "Director & State Controller",
    organization: "Dept of Consumer Affairs & Legal Metrology",
    state: "Rajasthan",
    district: "Jaipur",
    phone: "9000000001",
    avatar: "AD",
  },
  {
    id: "usr-lmo-1",
    email: "deepak.lmo@legalmetrology.gov.in",
    role: "lmo",
    name: "Deepak Verma",
    designation: "Legal Metrology Officer (Jaipur Central)",
    organization: "State Legal Metrology Dept",
    state: "Rajasthan",
    district: "Jaipur",
    phone: "9000012456",
    avatar: "DV",
  },
  {
    id: "usr-lmo-2",
    email: "kavita.lmo@legalmetrology.gov.in",
    role: "lmo",
    name: "Kavita Joshi",
    designation: "Senior Inspector (Weights & Measures)",
    organization: "State Legal Metrology Dept",
    state: "Uttar Pradesh",
    district: "Lucknow",
    phone: "9000045892",
    avatar: "KJ",
  },
  {
    id: "usr-lmo-3",
    email: "suresh.lmo@legalmetrology.gov.in",
    role: "lmo",
    name: "Suresh Nair",
    designation: "District Metrology Officer",
    organization: "District GATC Office",
    state: "Maharashtra",
    district: "Mumbai",
    phone: "9000078123",
    avatar: "SN",
  },
  {
    id: "usr-owner-1",
    email: "rajesh@example.com",
    role: "user",
    name: "Rajesh Kumar",
    organization: "Kumar Traders & Weighbridge",
    state: "Rajasthan",
    district: "Jaipur",
    phone: "9829011223",
    address: "42, Grain Market Road, Jaipur",
    avatar: "RK",
  },
  {
    id: "usr-owner-2",
    email: "sunita@example.com",
    role: "user",
    name: "Sunita Sharma",
    organization: "Sharma General Store",
    state: "Uttar Pradesh",
    district: "Lucknow",
    phone: "9839055441",
    address: "15, Hazratganj Market, Lucknow",
    avatar: "SS",
  },
  {
    id: "usr-owner-3",
    email: "anil@example.com",
    role: "user",
    name: "Anil Mehta",
    organization: "Mehta Fuel Station (HPCL)",
    state: "Maharashtra",
    district: "Mumbai",
    phone: "9820099887",
    address: "Plot 8, Highway Bypass, Mumbai",
    avatar: "AM",
  },
];

export const DEMO_ACCOUNTS = {
  admin: [
    { email: "admin@legalmetrology.gov.in", name: "Anjali Desai", org: "Dept of Consumer Affairs" }
  ],
  lmo: [
    { email: "deepak.lmo@legalmetrology.gov.in", name: "Deepak Verma", org: "Jaipur Central Dept" },
    { email: "kavita.lmo@legalmetrology.gov.in", name: "Kavita Joshi", org: "Lucknow Dept" },
    { email: "suresh.lmo@legalmetrology.gov.in", name: "Suresh Nair", org: "Mumbai District" }
  ],
  user: [
    { email: "rajesh@example.com", name: "Rajesh Kumar", org: "Kumar Traders (Jaipur)" },
    { email: "sunita@example.com", name: "Sunita Sharma", org: "Sharma General Store (Lucknow)" },
    { email: "anil@example.com", name: "Anil Mehta", org: "Mehta Fuel Station (Mumbai)" }
  ]
};

export const INITIAL_INSTRUMENTS = [
  {
    id: "inst-101",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    type: "Electronic Weighing Machine",
    model: "MDL-840",
    serialNumber: "SER-1001",
    manufacturer: "Avery India Ltd",
    capacity: "500 kg",
    accuracy: "Class III",
    location: "Kumar Traders, Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    status: "verified",
    lastVerificationDate: "2025-08-15",
    validityEndDate: "2026-08-14",
  },
  {
    id: "inst-102",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    type: "Platform Scale",
    model: "MDL-320",
    serialNumber: "SER-1002",
    manufacturer: "Essae Digitronics",
    capacity: "1000 kg",
    accuracy: "Class III",
    location: "Kumar Traders Warehouse, Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    status: "unverified",
    lastVerificationDate: null,
    validityEndDate: null,
  },
  {
    id: "inst-103",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    type: "Counter Scale",
    model: "MDL-115",
    serialNumber: "SER-1003",
    manufacturer: "Precision Scales Pvt Ltd",
    capacity: "50 kg",
    accuracy: "Class II",
    location: "Retail Counter, Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    status: "verified",
    lastVerificationDate: "2024-10-02",
    validityEndDate: "2025-10-01", // expiring soon
  },
  {
    id: "inst-104",
    ownerId: "usr-owner-2",
    ownerName: "Sunita Sharma",
    ownerOrg: "Sharma General Store",
    type: "Weighing Scale",
    model: "MDL-210",
    serialNumber: "SER-1004",
    manufacturer: "Contech Instruments",
    capacity: "100 kg",
    accuracy: "Class III",
    location: "Hazratganj Store, Lucknow",
    state: "Uttar Pradesh",
    district: "Lucknow",
    status: "verified",
    lastVerificationDate: "2025-07-20",
    validityEndDate: "2026-07-19",
  },
  {
    id: "inst-105",
    ownerId: "usr-owner-2",
    ownerName: "Sunita Sharma",
    ownerOrg: "Sharma General Store",
    type: "Spring Balance",
    model: "MDL-404",
    serialNumber: "SER-1005",
    manufacturer: "Precision Scales Pvt Ltd",
    capacity: "50 kg",
    accuracy: "Class III",
    location: "Hazratganj Store, Lucknow",
    state: "Uttar Pradesh",
    district: "Lucknow",
    status: "unverified",
    lastVerificationDate: null,
    validityEndDate: null,
  },
  {
    id: "inst-106",
    ownerId: "usr-owner-3",
    ownerName: "Anil Mehta",
    ownerOrg: "Mehta Fuel Station (HPCL)",
    type: "Fuel Dispensing Pump",
    model: "MDL-990-DX",
    serialNumber: "SER-1006",
    manufacturer: "HDPE Metering Co",
    capacity: "50 L/min",
    accuracy: "Class II",
    location: "Bay 1, Highway Bypass, Mumbai",
    state: "Maharashtra",
    district: "Mumbai",
    status: "verified",
    lastVerificationDate: "2025-09-01",
    validityEndDate: "2026-08-31",
  },
  {
    id: "inst-107",
    ownerId: "usr-owner-3",
    ownerName: "Anil Mehta",
    ownerOrg: "Mehta Fuel Station (HPCL)",
    type: "Fuel Dispensing Pump",
    model: "MDL-990-DX",
    serialNumber: "SER-1007",
    manufacturer: "HDPE Metering Co",
    capacity: "50 L/min",
    accuracy: "Class II",
    location: "Bay 2, Highway Bypass, Mumbai",
    state: "Maharashtra",
    district: "Mumbai",
    status: "unverified",
    lastVerificationDate: null,
    validityEndDate: null,
  }
];

export const INITIAL_APPLICATIONS = [
  {
    id: "APP-2025-0098",
    instrumentId: "inst-101",
    instrumentName: "Electronic Weighing Machine (500 kg)",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    district: "Jaipur",
    state: "Rajasthan",
    type: "re-verification",
    verificationLocation: "on-site",
    status: "completed",
    result: "pass",
    assignedLmoId: "usr-lmo-1",
    assignedLmoName: "Deepak Verma",
    appliedDate: "2025-08-10",
    scheduledDate: "2025-08-14",
    scheduledTime: "11:30 AM",
    verificationDate: "2025-08-15",
    certificateNumber: "LM-2025-A8F192C0",
    observations: {
      readings: "Standard weight: 100kg, Measured: 100.01kg",
      errorFound: "+0.01kg",
      toleranceWithin: true,
      remarks: "Within permissible tolerance limits. Tamper seal verified.",
      sealNumber: "SEAL-RAJ-8812"
    }
  },
  {
    id: "APP-2025-0097",
    instrumentId: "inst-102",
    instrumentName: "Platform Scale (1000 kg)",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    district: "Jaipur",
    state: "Rajasthan",
    type: "initial",
    verificationLocation: "on-site",
    status: "submitted", // Pending assignment by Admin
    result: null,
    assignedLmoId: null,
    assignedLmoName: null,
    appliedDate: "2025-09-20",
    scheduledDate: null,
    scheduledTime: null,
    verificationDate: null,
    certificateNumber: null,
    observations: null
  },
  {
    id: "APP-2025-0096",
    instrumentId: "inst-103",
    instrumentName: "Counter Scale (50 kg)",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    district: "Jaipur",
    state: "Rajasthan",
    type: "re-verification",
    verificationLocation: "lab",
    status: "assigned", // Assigned to Deepak Verma, ready to be scheduled
    result: null,
    assignedLmoId: "usr-lmo-1",
    assignedLmoName: "Deepak Verma",
    appliedDate: "2025-09-18",
    scheduledDate: null,
    scheduledTime: null,
    verificationDate: null,
    certificateNumber: null,
    observations: null
  },
  {
    id: "APP-2025-0095",
    instrumentId: "inst-104",
    instrumentName: "Weighing Scale (100 kg)",
    ownerId: "usr-owner-2",
    ownerName: "Sunita Sharma",
    ownerOrg: "Sharma General Store",
    district: "Lucknow",
    state: "Uttar Pradesh",
    type: "re-verification",
    verificationLocation: "lab",
    status: "completed",
    result: "pass",
    assignedLmoId: "usr-lmo-2",
    assignedLmoName: "Kavita Joshi",
    appliedDate: "2025-07-15",
    scheduledDate: "2025-07-19",
    scheduledTime: "10:00 AM",
    verificationDate: "2025-07-20",
    certificateNumber: "LM-2025-B4E991A1",
    observations: {
      readings: "Standard weight: 50kg, Measured: 50.00kg",
      errorFound: "0.00kg",
      toleranceWithin: true,
      remarks: "High precision calibration passed.",
      sealNumber: "SEAL-UP-3419"
    }
  },
  {
    id: "APP-2025-0094",
    instrumentId: "inst-105",
    instrumentName: "Spring Balance (50 kg)",
    ownerId: "usr-owner-2",
    ownerName: "Sunita Sharma",
    ownerOrg: "Sharma General Store",
    district: "Lucknow",
    state: "Uttar Pradesh",
    type: "initial",
    verificationLocation: "on-site",
    status: "scheduled", // Scheduled by Kavita Joshi
    result: null,
    assignedLmoId: "usr-lmo-2",
    assignedLmoName: "Kavita Joshi",
    appliedDate: "2025-09-22",
    scheduledDate: "2025-09-30",
    scheduledTime: "02:00 PM",
    verificationDate: null,
    certificateNumber: null,
    observations: null
  },
  {
    id: "APP-2025-0093",
    instrumentId: "inst-106",
    instrumentName: "Fuel Dispensing Pump (Bay 1)",
    ownerId: "usr-owner-3",
    ownerName: "Anil Mehta",
    ownerOrg: "Mehta Fuel Station (HPCL)",
    district: "Mumbai",
    state: "Maharashtra",
    type: "re-verification",
    verificationLocation: "on-site",
    status: "completed",
    result: "pass",
    assignedLmoId: "usr-lmo-3",
    assignedLmoName: "Suresh Nair",
    appliedDate: "2025-08-25",
    scheduledDate: "2025-08-30",
    scheduledTime: "10:30 AM",
    verificationDate: "2025-09-01",
    certificateNumber: "LM-2025-C22998F4",
    observations: {
      readings: "Delivery measure 5L test: 5002 ml",
      errorFound: "+2 ml (permissible <= 25 ml)",
      toleranceWithin: true,
      remarks: "Meter pulsar and totalizer seals intact.",
      sealNumber: "SEAL-MH-9014"
    }
  },
  {
    id: "APP-2025-0092",
    instrumentId: "inst-107",
    instrumentName: "Fuel Dispensing Pump (Bay 2)",
    ownerId: "usr-owner-3",
    ownerName: "Anil Mehta",
    ownerOrg: "Mehta Fuel Station (HPCL)",
    district: "Mumbai",
    state: "Maharashtra",
    type: "initial",
    verificationLocation: "on-site",
    status: "submitted",
    result: null,
    assignedLmoId: null,
    assignedLmoName: null,
    appliedDate: "2025-09-24",
    scheduledDate: null,
    scheduledTime: null,
    verificationDate: null,
    certificateNumber: null,
    observations: null
  }
];

export const INITIAL_CERTIFICATES = [
  {
    certificateNumber: "LM-2025-A8F192C0",
    applicationId: "APP-2025-0098",
    instrumentId: "inst-101",
    instrumentName: "Electronic Weighing Machine (500 kg)",
    serialNumber: "SER-1001",
    model: "MDL-840",
    ownerId: "usr-owner-1",
    ownerName: "Rajesh Kumar",
    ownerOrg: "Kumar Traders & Weighbridge",
    address: "42, Grain Market Road, Jaipur",
    lmoName: "Deepak Verma",
    lmoDesignation: "Legal Metrology Officer (Jaipur Central)",
    verificationDate: "2025-08-15",
    validityFrom: "2025-08-15",
    validityTo: "2026-08-14",
    result: "Pass",
    status: "valid",
    sealNumber: "SEAL-RAJ-8812",
    qrData: "VERIFIED|LM-2025-A8F192C0|SER-1001|VALID_TILL_2026-08-14"
  },
  {
    certificateNumber: "LM-2025-B4E991A1",
    applicationId: "APP-2025-0095",
    instrumentId: "inst-104",
    instrumentName: "Weighing Scale (100 kg)",
    serialNumber: "SER-1004",
    model: "MDL-210",
    ownerId: "usr-owner-2",
    ownerName: "Sunita Sharma",
    ownerOrg: "Sharma General Store",
    address: "15, Hazratganj Market, Lucknow",
    lmoName: "Kavita Joshi",
    lmoDesignation: "Senior Inspector (Weights & Measures)",
    verificationDate: "2025-07-20",
    validityFrom: "2025-07-20",
    validityTo: "2026-07-19",
    result: "Pass",
    status: "valid",
    sealNumber: "SEAL-UP-3419",
    qrData: "VERIFIED|LM-2025-B4E991A1|SER-1004|VALID_TILL_2026-07-19"
  },
  {
    certificateNumber: "LM-2025-C22998F4",
    applicationId: "APP-2025-0093",
    instrumentId: "inst-106",
    instrumentName: "Fuel Dispensing Pump (Bay 1)",
    serialNumber: "SER-1006",
    model: "MDL-990-DX",
    ownerId: "usr-owner-3",
    ownerName: "Anil Mehta",
    ownerOrg: "Mehta Fuel Station (HPCL)",
    address: "Plot 8, Highway Bypass, Mumbai",
    lmoName: "Suresh Nair",
    lmoDesignation: "District Metrology Officer",
    verificationDate: "2025-09-01",
    validityFrom: "2025-09-01",
    validityTo: "2026-08-31",
    result: "Pass",
    status: "valid",
    sealNumber: "SEAL-MH-9014",
    qrData: "VERIFIED|LM-2025-C22998F4|SER-1006|VALID_TILL_2026-08-31"
  }
];

export const INITIAL_ACTIVITIES = [
  { id: "act-1", time: "10 mins ago", role: "admin", text: "Admin portal accessed by Anjali Desai" },
  { id: "act-2", time: "25 mins ago", role: "lmo", text: "Officer Deepak Verma reviewed schedule for Jaipur" },
  { id: "act-3", time: "2 hours ago", role: "user", text: "Application APP-2025-0097 submitted by Rajesh Kumar" },
  { id: "act-4", time: "Yesterday", role: "lmo", text: "Inspection scheduled for APP-2025-0094 by Kavita Joshi" }
];
